version: '3.7'

services:
  concert-service:
    build:
      dockerfile: Dockerfile
    container_name: concert-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/concert
      SPRING_DATASOURCE_USERNAME: concert
      SPRING_DATASOURCE_PASSWORD: concert1234
      SPRING_DATA_REDIS_HOST: redis
      QUEUE_WAITING_KEY: concertWaitingQueue
      QUEUE_ACTIVE_KEY: concertActiveQueue
      SPRING_PROFILES_ACTIVE: local
    ports:
      - "8080:8080"
    depends_on:
      - mysql
      - redis
    deploy:
      resources:
        limits:
          cpus: "2.00"
          memory: 4GB
    networks:
      - concert-network

  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: concert
      MYSQL_USER: concert
      MYSQL_PASSWORD: concert1234
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - concert-network

  redis:
    image: redis:7.4.1-alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - concert-network

networks:
  concert-network:

volumes:
  mysql-data:
  redis-data: